server:
  port: 8888
  tomcat:
    basedir: /tmp/tomcat
spring:
  datasource:
    #   数据源基本配置
    username: root
    password: password
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/d_blog
    type: com.alibaba.druid.pool.DruidDataSource
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
  mvc:
    date-format: yyyy-MM-dd hh:mm:ss
    favicon:
          enabled: false
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB
mybatis:
  type-aliases-package: com.diao.pojo
  cache-enabled: true
  mapper-locations: classpath:mybatis/*.xml
  config-location: classpath:mybatis-config.xml

teng:
  xun:

logging:
  file:
    path: blog.log
  level:
    root: info
    com.diao.mapper: debug